POST http://localhost:8888/api/Users/signup HTTP/1.1
content-type: application/json

{ "firstName":"Noodle House",
 "lastName":"Cuisine", 
 "email":"ksgerges@mum.edu",
 "password":"123456"
 }
###
POST http://localhost:8888/api/Users/findbyemail HTTP/1.1
content-type: application/json

{ 
 "email":"ksgerges@mum.edu"
}

###
POST http://localhost:8888/api/Users/signin HTTP/1.1
content-type: application/json

{ 
 "email":"ksgerges@mum.edu",
 "password":"123456"
}
###
POST http://localhost:8888/api/Users/protected HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjVkODQzYWJiMTM1MmY3MmQ5MDc0MTRmMCIsImlhdCI6MTU2OTAxNTMxMCwiZXhwIjoxNTcxNjA3MzEwLCJhdWQiOiJodHRwOi8vbXlzb2Z0Y29ycC5pbiIsImlzcyI6Ik1VTSIsInN1YiI6InNvbWVAdXNlci5jb20ifQ.iCnpcJDByJT2bb22yIIiL3IhHn93779gFObnfSf1kes2UgmedDF2KLs9-BqV_zqtbp7qftaAtB1h5Sh6Wz5kuA

{ 
 "email":"ksgerges@mum.edu"
}

###